stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - sonarqube
  - postman
  - cypress
  - docker

build:  
  stage: build  
  script:      
    -  ./gradlew build -x test     
    -  ./gradlew.bat --stop 

test:         
  stage: test  
  script:  
    -  ./gradlew test     
    -  ./gradlew.bat --stop


sonarqube-check:
  stage: sonarqube
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: gradle sonarqube
  allow_failure: true
  only:
    - master 

postman_tests:
  stage: postman
  script:
      - cd C:\Users\Lenovo\AppData\Roaming\npm
      - ./newman run https://www.getpostman.com/collections/934646ca67717ac52dff

cypress_tests:
  stage: cypress
  image: cypress/base:10
  script:
    - cd wear_me_web
    - npx cypress run


docker:     
  stage: docker    
  script:     
    - cd wear_me_web
    - docker build -t frontendcontainer .    
    - cd ..    
    - replace "C:\Users\Lenovo\Desktop\individualproject_veronikavaleva\override\prod\application.properties" "C:\Users\Lenovo\Desktop\individualproject_veronikavaleva\src\main\resources"    
    - ./gradlew build -x test   
    - docker build -t backendcontainer .    
    - replace "C:\Users\Lenovo\Desktop\individualproject_veronikavaleva\override\test\application.properties" "C:\Users\Lenovo\Desktop\individualproject_veronikavaleva\src\main\resources"    
    - ./gradlew.bat --stop




